name: Test

on:
  pull_request:
  push:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - 'pypy-3.6'
          - 'pypy-3.7'
          - 'pypy-3.8'
          - 'pypy-3.9'
        toxenv: [py]
        include:
          - python-version: '3.6'
            toxenv: lint
            os: ubuntu-latest
          - python-version: '3.6'
            toxenv: typing
            os: ubuntu-latest
          - python-version: '3.7'
            toxenv: py-oldsetup
            os: ubuntu-latest
        exclude:
          - os: macos-latest
            python-version: 'pypy-3.6'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade --upgrade-strategy=eager tox
          virtualenv --upgrade-embed-wheels

      - name: Install Mercurial
        if: startsWith(matrix.os, 'macos-')
        run: brew install mercurial

      - name: Run tests with coverage
        if: startsWith(matrix.toxenv, 'py')
        run: tox -e py -- -vv --cov-report=xml

      - name: Run generic tests
        if: "!startsWith(matrix.toxenv, 'py')"
        run: tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Codecov
        if: startsWith(matrix.toxenv, 'py')
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false

# vim:set et sts=2:
